version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    container_name: gitlab
    hostname: "${GITLAB_HOST}"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}'
        gitlab_rails['time_zone'] = '${TZ}'

    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - ./volumes/config:/etc/gitlab
      - ./volumes/logs:/var/log/gitlab
      - ./volumes/data:/var/opt/gitlab
    depends_on:
      - redis
      - postgres
    networks:
      - gitlab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/-/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:${REDIS_VERSION}
    container_name: gitlab_redis
    command: ["--loglevel", "warning"]
    volumes:
      - ./volumes/redis:/data
    restart: always
    networks:
      - gitlab
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: gitlab_postgres
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_DB: gitlabhq_production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - gitlab
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gitlab"]
      interval: 30s
      timeout: 10s
      retries: 5

  runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    container_name: gitlab_runner
    restart: always
    environment:
      CI_SERVER_URL: https://${GITLAB_HOST}
    volumes:
      - ./volumes/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    depends_on:
      gitlab:
        condition: service_healthy

networks:
  gitlab:
    driver: bridge
