#!/bin/bash
# ================================================================
# Harbor Installer Script
# Tải, cấu hình và triển khai Harbor tự động
# ================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"

cd "${PROJECT_DIR}"

# Load biến
if [ -f .env ]; then
    source .env
elif [ -f .env.default ]; then
    source .env.default
else
    echo "❌ Không tìm thấy .env hoặc .env.default"
    exit 1
fi

HARBOR_VERSION="${HARBOR_VERSION:-v2.15.1}"
HARBOR_HOST="${HARBOR_HOST:-harbor.local}"
HARBOR_PORT="${HARBOR_PORT:-443}"
HARBOR_ADMIN_PASSWORD="${HARBOR_ADMIN_PASSWORD:-Harbor12345}"
HARBOR_DB_PASSWORD="${HARBOR_DB_PASSWORD:-change_me_to_strong_password}"
HARBOR_DATA_DIR="${HARBOR_DATA_DIR:-/data/harbor}"
HARBOR_CERT_DIR="${HARBOR_CERT_DIR:-./ssl}"
HARBOR_WITH_TRIVY="${HARBOR_WITH_TRIVY:-true}"
INSTALLER_DIR="${PROJECT_DIR}/harbor-installer"

echo "================================================"
echo "  Harbor Installer"
echo "  Version: ${HARBOR_VERSION}"
echo "  Host:    ${HARBOR_HOST}:${HARBOR_PORT}"
echo "  Data:    ${HARBOR_DATA_DIR}"
echo "  Trivy:   ${HARBOR_WITH_TRIVY}"
echo "================================================"

# ---- 1. Kiểm tra prerequisites ----
echo ""
echo "🔍 Kiểm tra prerequisites..."

command -v docker >/dev/null 2>&1 || { echo "❌ Docker chưa cài đặt"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "❌ OpenSSL chưa cài đặt"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "❌ Docker Compose plugin chưa cài đặt"; exit 1; }

echo "  ✅ Docker: $(docker --version | awk '{print $3}' | tr -d ',')"
echo "  ✅ Compose: $(docker compose version --short)"
echo "  ✅ OpenSSL: $(openssl version | awk '{print $2}')"

# ---- 2. Sinh SSL cert (nếu chưa có) ----
if [ ! -f "${HARBOR_CERT_DIR}/${HARBOR_HOST}.crt" ]; then
    echo ""
    echo "🔐 Sinh SSL certificates..."
    bash "${SCRIPT_DIR}/generate-ssl.sh"
else
    echo ""
    echo "✅ SSL cert đã tồn tại: ${HARBOR_CERT_DIR}/${HARBOR_HOST}.crt"
fi

# ---- 3. Cấu hình Docker daemon trust cert ----
echo ""
echo "🐳 Cấu hình Docker daemon trust cert..."
DOCKER_CERT_DIR="/etc/docker/certs.d/${HARBOR_HOST}"

if [ "${HARBOR_PORT}" != "443" ]; then
    DOCKER_CERT_DIR="/etc/docker/certs.d/${HARBOR_HOST}:${HARBOR_PORT}"
fi

sudo mkdir -p "${DOCKER_CERT_DIR}"
sudo cp "${HARBOR_CERT_DIR}/${HARBOR_HOST}.cert" "${DOCKER_CERT_DIR}/"
sudo cp "${HARBOR_CERT_DIR}/${HARBOR_HOST}.key" "${DOCKER_CERT_DIR}/"
sudo cp "${HARBOR_CERT_DIR}/ca.crt" "${DOCKER_CERT_DIR}/"
echo "  ✅ Cert đã copy vào ${DOCKER_CERT_DIR}"

echo "  🔄 Restart Docker daemon..."
sudo systemctl restart docker

# ---- 4. Tải Harbor installer ----
if [ ! -d "${INSTALLER_DIR}" ]; then
    echo ""
    echo "📥 Tải Harbor ${HARBOR_VERSION} online installer..."
    HARBOR_URL="https://github.com/goharbor/harbor/releases/download/${HARBOR_VERSION}/harbor-online-installer-${HARBOR_VERSION}.tgz"

    curl -fSL "${HARBOR_URL}" -o /tmp/harbor-installer.tgz
    tar xzf /tmp/harbor-installer.tgz -C "${PROJECT_DIR}"
    mv "${PROJECT_DIR}/harbor" "${INSTALLER_DIR}"
    rm -f /tmp/harbor-installer.tgz
    echo "  ✅ Đã tải và giải nén vào ${INSTALLER_DIR}"
else
    echo ""
    echo "✅ Harbor installer đã tồn tại: ${INSTALLER_DIR}"
fi

# ---- 5. Sinh harbor.yml từ template ----
echo ""
echo "📝 Sinh harbor.yml..."

CERT_ABSOLUTE_PATH="$(cd "${HARBOR_CERT_DIR}" && pwd)"

cat > "${INSTALLER_DIR}/harbor.yml" <<EOF
# ================================================================
# Harbor Configuration - Auto-generated by install.sh
# Harbor ${HARBOR_VERSION} | SSL Self-Signed
# ================================================================

hostname: ${HARBOR_HOST}

http:
  port: 80

https:
  port: ${HARBOR_PORT}
  certificate: ${CERT_ABSOLUTE_PATH}/${HARBOR_HOST}.crt
  private_key: ${CERT_ABSOLUTE_PATH}/${HARBOR_HOST}.key

harbor_admin_password: ${HARBOR_ADMIN_PASSWORD}

database:
  password: ${HARBOR_DB_PASSWORD}
  max_idle_conns: 100
  max_open_conns: 900
  conn_max_lifetime: 5m
  conn_max_idle_time: 0

data_volume: ${HARBOR_DATA_DIR}

trivy:
  ignore_unfixed: false
  skip_update: false
  skip_java_db_update: false
  db_repository: ghcr.io/aquasecurity/trivy-db
  java_db_repository: ghcr.io/aquasecurity/trivy-java-db
  offline_scan: false
  security_check: vuln,config,secret
  insecure: false
  timeout: 5m0s

jobservice:
  max_job_workers: 10
  max_job_duration_hours: 24
  job_loggers:
    - STD_OUTPUT
    - FILE
  logger_sweeper_duration: 1

notification:
  webhook_job_max_retry: 3
  webhook_job_http_client_timeout: 3

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.15.0

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false

cache:
  enabled: false
  expire_hours: 24
EOF

echo "  ✅ harbor.yml đã sinh tại ${INSTALLER_DIR}/harbor.yml"

# ---- 6. Tạo data directory ----
echo ""
echo "📁 Tạo data directory..."
sudo mkdir -p "${HARBOR_DATA_DIR}"
echo "  ✅ ${HARBOR_DATA_DIR}"

# ---- 7. Chạy Harbor installer ----
echo ""
echo "🚀 Chạy Harbor installer..."
cd "${INSTALLER_DIR}"

INSTALL_ARGS=""
if [ "${HARBOR_WITH_TRIVY}" = "true" ]; then
    INSTALL_ARGS="--with-trivy"
fi

sudo ./install.sh ${INSTALL_ARGS}

echo ""
echo "================================================"
echo "  ✅ Harbor đã triển khai thành công!"
echo ""
echo "  🌐 URL:      https://${HARBOR_HOST}:${HARBOR_PORT}"
echo "  👤 User:     admin"
echo "  🔑 Password: ${HARBOR_ADMIN_PASSWORD}"
echo ""
echo "  📦 Docker login:"
echo "     docker login ${HARBOR_HOST}:${HARBOR_PORT}"
echo ""
echo "  📦 Push image:"
echo "     docker tag myimage ${HARBOR_HOST}:${HARBOR_PORT}/library/myimage:latest"
echo "     docker push ${HARBOR_HOST}:${HARBOR_PORT}/library/myimage:latest"
echo "================================================"
